const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto').webcrypto;
const core=require('../src/app.js');const root=path.join(__dirname,'..');const envelope=JSON.parse(fs.readFileSync(path.join(root,'data/library-envelope.json')));const payload=JSON.parse(envelope.payload);
test('real cumulative envelope is valid',async()=>{assert.equal((await core.verifyEnvelope(envelope,null,crypto)).records.length,payload.records.length)});
test('wrong domain, broken checksum, missing old IDs rejected',async()=>{await assert.rejects(core.verifyEnvelope({...envelope,domain_id:'myopia'},null,crypto));await assert.rejects(core.verifyEnvelope({...envelope,sha256:'bad'},null,crypto));assert.throws(()=>core.validPayload({...payload,records:payload.records.slice(1)},payload))});
test('untrusted source text escapes script and attribute injection',()=>{const bad='<img src=x onerror="alert(1)"></script>';assert(!core.escape(bad).includes('<'));assert.equal(core.safeURL('javascript:alert(1)'),'');assert.equal(core.safeURL('https://user:secret@example.com'),'')});
test('Chinese and English Whipple aliases map to reviewed operation topic',()=>{const r={id:'x',title:'Pancreaticoduodenectomy study',topic_ids:['pancreas-whipple']};assert(core.search(r,'Whipple',payload.taxonomy));assert(core.search(r,'胰十二指肠切除',payload.taxonomy));assert(!core.search(r,'胆囊癌',payload.taxonomy))});
test('multiple filters and empty results do not alter cumulative data',()=>{const before=payload.records.length;const selected=core.select(payload.records,{kind:'article',language:'英文'},'Whipple',payload.taxonomy);assert(selected.length>0);assert(selected.every(r=>r.kind==='article'&&r.language==='英文'));assert.equal(core.select(payload.records,{},'UNLIKELY-NONMEDICAL-QUERY-xy123',payload.taxonomy).length,0);assert.equal(payload.records.length,before)});
test('ID and note content are searchable',()=>{const r=payload.records.find(x=>x.id==='P001');assert(core.search(r,'P001',payload.taxonomy));assert(core.search(r,r.note.question.slice(0,5),payload.taxonomy))});
test('playback gate needs permission AND successful embed test',()=>{const r={video:{embed_url:'https://player.vimeo.com/video/123',embed_permission:'confirmed',embed_test:'not_tested'}};assert(!core.embedAllowed(r));r.video.embed_test='passed';assert(core.embedAllowed(r));r.video.embed_url='https://evil.example/player';assert(!core.embedAllowed(r))});
test('single HTML embeds all original record IDs and no eager iframe',()=>{const html=fs.readFileSync(path.join(root,'site/index.html'),'utf8');assert(html.includes('展开完整阅读笔记'));assert(!/<iframe\b/i.test(html));assert(html.includes('credentials:\'omit\''));assert(!html.includes('no-cors'));for(const r of payload.records)assert(html.includes('"id":"'+r.id+'"'))});

test('malformed navigation or note data cannot replace the working snapshot',()=>{assert.throws(()=>core.validPayload({...payload,taxonomy:{topics:{}}},payload));assert.throws(()=>core.validPayload({...payload,candidates:null},payload));const rs=JSON.parse(JSON.stringify(payload.records));rs[0].note.results=null;assert.throws(()=>core.validPayload({...payload,records:rs},payload))});
