'use strict';
const HPBCore=(()=>{
 const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const normalize=s=>String(s??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[\s_—–-]+/g,' ');
 const safeURL=u=>{try{const x=new URL(u);return ['https:','http:'].includes(x.protocol)&&!x.username&&!x.password?x.href:''}catch{return ''}};
 function search(r,q,tax){const n=normalize(q).trim();if(!n)return true;const hay=normalize([r.id,r.title,r.zh_title,r.authors,r.doi,r.pmid,r.topic,(r.topic_tags||[]).join(' '),JSON.stringify(r.note||{})].join(' '));const group=tax.topics.find(t=>t.aliases.some(a=>normalize(a)===n));return group?group.aliases.some(a=>hay.includes(normalize(a)))||r.topic_ids?.includes(group.id):n.split(/\s+/).every(w=>hay.includes(w));}
 function select(records,f,q,tax){return records.filter(r=>search(r,q,tax)&&Object.entries(f).every(([k,v])=>!v||(k==='topic_ids'?(r.topic_ids||[]).includes(v):k==='organ'?(r.organs||[r.organ]).includes(v):String(r[k]??'')===v)));}
 function validPayload(p,base){if(p.domain_id!=='hpb-surgery'||p.schema_version!==1||!Array.isArray(p.records)||!Array.isArray(p.candidates)||!Array.isArray(p.coverage)||!Array.isArray(p.taxonomy?.topics)||!Array.isArray(p.taxonomy?.organs)||!p.state||!p.deployment||!p.data_version||!Number.isFinite(Date.parse(p.generated_at)))throw Error('领域或结构版本不匹配');const ids=new Set();for(const r of p.records){if(!/^[A-Za-z0-9_.-]+$/.test(r.id)||ids.has(r.id)||!r.title)throw Error('记录ID或题名异常');ids.add(r.id);if(!Array.isArray(r.topic_ids)||!Array.isArray(r.linked_article_ids)||!Array.isArray(r.linked_video_ids)||typeof r.title!=='string'||!['article','society','video','course','portal','lead'].includes(r.kind))throw Error('记录结构无效');if(r.note&&(!Array.isArray(r.note.results)||!Array.isArray(r.note.limitations)||!Array.isArray(r.note.sources)))throw Error('阅读笔记结构无效');if(r.kind==='article'&&(!r.note||!r.note.read_depth))throw Error('文献缺少阅读状态');}if(base&&!base.records.every(r=>ids.has(r.id)))throw Error('累计数据缺失已有ID');return p;}
 async function verifyEnvelope(e,base,cryptoAPI){if(e.domain_id!=='hpb-surgery'||e.schema_version!==1||typeof e.payload!=='string'||e.payload.length>50000000)throw Error('更新封装无效');const sum=Array.from(new Uint8Array(await cryptoAPI.subtle.digest('SHA-256',new TextEncoder().encode(e.payload)))).map(x=>x.toString(16).padStart(2,'0')).join('');if(sum!==e.sha256)throw Error('数据校验值不符');const p=validPayload(JSON.parse(e.payload),base);if(p.data_version!==e.data_version)throw Error('版本与封装不符');return p;}
 const embedAllowed=r=>r.video?.embed_permission==='confirmed'&&r.video?.embed_test==='passed'&&/^https:\/\/(www\.youtube-nocookie\.com\/embed\/[\w-]+|player\.vimeo\.com\/video\/\d+)(?:\?.*)?$/.test(r.video.embed_url||'');
 return {escape,normalize,safeURL,search,select,validPayload,verifyEnvelope,embedAllowed};
})();
if(typeof module!=='undefined')module.exports=HPBCore;
if(typeof document!=='undefined')(()=>{
const {$}= { $:id=>document.getElementById(id)};const E=HPBCore.escape,U=HPBCore.safeURL;
const embedded=HPBCore.validPayload(JSON.parse($('data').textContent)),trustedDeployment={...embedded.deployment};
let data=embedded,view='library',page=1,sort='default',q='',filters={},personal={domain_id:'hpb-surgery',schema_version:1,favorites:[],notes:{},read:{}},storageOK=true;
try{const s=localStorage.getItem('hpb-personal-v1');if(s)personal={...personal,...JSON.parse(s)}}catch{storageOK=false}
const fields=[['organ','器官/领域'],['topic_ids','疾病或术式'],['approach','手术路径'],['resource_type','资源类型'],['year','年份'],['language','语言'],['source','来源/平台'],['fulltext_status','全文取得情况'],['read_depth','笔记阅读范围'],['verification_status','核验状态']];
const date=s=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'尚无成功记录';
const link=(u,t)=>U(u)?`<a href="${E(U(u))}" target="_blank" rel="noopener noreferrer">${E(t)}</a>`:`<span class="notice">链接待核</span>`;
const chip=(s,c='')=>`<span class="chip ${c}">${E(s||'未知')}</span>`;
function persist(){try{localStorage.setItem('hpb-personal-v1',JSON.stringify(personal))}catch{storageOK=false;$('personal-status').textContent='浏览器未允许保存；本次修改只在内存中，请立即备份。'}}
function readURL(){const p=new URLSearchParams(location.search);q=p.get('q')||'';view=p.get('view')||'library';sort=p.get('sort')||'default';filters=Object.fromEntries(fields.map(([k])=>[k,p.get(k)||'']));$('search').value=q;$('sort').value=sort;}
function writeURL(preserveAnchor=false){const p=new URLSearchParams();if(q)p.set('q',q);if(view!=='library')p.set('view',view);if(sort!=='default')p.set('sort',sort);for(const[k,v]of Object.entries(filters))if(v)p.set(k,v);try{history.replaceState(null,'',location.pathname+(p.size?'?'+p.toString():'')+(preserveAnchor?location.hash:''))}catch{}}
function values(k){return k==='topic_ids'?data.taxonomy.topics.map(t=>[t.id,t.label]):Array.from(new Set(data.records.flatMap(r=>k==='organ'?(r.organs||[r.organ]):r[k]).filter(x=>x!==null&&x!==undefined&&x!==''))).sort((a,b)=>k==='year'?Number(b)-Number(a):String(a).localeCompare(String(b),'zh')).map(v=>[v,v]);}
function filterUI(){const control=([k,label])=>`<label>${E(label)}<select data-filter="${k}" aria-label="${E(label)}"><option value="">全部</option>${values(k).map(([v,t])=>`<option value="${E(v)}" ${String(filters[k])===String(v)?'selected':''}>${E(t)}</option>`).join('')}</select></label>`;const primary=['organ','topic_ids','resource_type'];$('filters').innerHTML=fields.filter(([k])=>primary.includes(k)).map(control).join('')+`<details class="extra-filters" ${fields.some(([k])=>!primary.includes(k)&&filters[k])?'open':''}><summary>更多筛选：路径、年份、语言、全文与核验状态</summary><div class="filters">${fields.filter(([k])=>!primary.includes(k)).map(control).join('')}</div></details>`;}
function navUI(){ $('nav').innerHTML=`<button data-all="true">全部资源 <span class="count">${data.records.length}</span></button>`+data.taxonomy.organs.map((o,i)=>{const list=data.taxonomy.topics.filter(t=>t.organ===o);const count=data.records.filter(r=>(r.organs||[r.organ]).includes(o)).length;return `<details ${i<2?'open':''}><summary>${E(o)} <span class="count">${count}</span></summary><button data-organ="${E(o)}">本板块全部</button>${list.map(t=>`<button data-topic="${E(t.id)}" class="${filters.topic_ids===t.id?'chosen':''}">${E(t.label)} <span class="count">${data.records.filter(r=>r.topic_ids.includes(t.id)).length}</span></button>`).join('')}</details>`}).join('');}
function header(){const rec=data.records,stats=[['篇文献',rec.filter(x=>x.kind==='article').length],['篇正文重点笔记',rec.filter(x=>x.note?.read_depth==='正文重点核对').length],['条具体视频',rec.filter(x=>x.kind==='video').length],['个课程模块',rec.filter(x=>x.kind==='course').length],['个合集入口',rec.filter(x=>x.kind==='portal').length]];$('stats').innerHTML=stats.map(([t,n])=>`<div class="stat"><strong>${n}</strong><span>${t}</span></div>`).join('');const s=data.state||{};$('run-status').innerHTML=`<span>最近尝试：${date(s.last_attempt)}</span><span>最近成功检索：${date(s.last_successful_search)}</span><span>最近成功发布：${date(s.last_successful_publish)}</span>`;const coverageTime=s.last_complete_coverage_through||s.last_successful_search;const age=coverageTime?(Date.now()-Date.parse(coverageTime))/86400000:Infinity;const dep=data.deployment||{};$('run-detail').innerHTML=`<p>${age>10?'⚠ 检索状态未达到最近10天内全来源成功，请查看失败及人工补查范围。':'最近一次成功检索在10天内；本次尝试状态与来源覆盖范围见下方。'}</p>${s.last_complete_coverage_through?`<p>各配置来源累计覆盖水位（取最早者）：${date(s.last_complete_coverage_through)}。完成检索的时间与覆盖窗口分别记录。</p>`:''}<p>云端：${dep.deployed?'已经部署':'尚未部署'}；周调度：${dep.schedule_enabled?'已启用':'尚未启用'}；真实定时运行：${dep.observed_scheduled_run?E(dep.observed_scheduled_run):'尚未观察到'}。排期：每周一北京时间09:17。</p><p>最近一次更新状态：${E({running:'正在运行',success:'本次请求范围检索已完成',complete:'本次请求范围检索已完成',partial:'部分完成，请查看失败项',failed:'失败，结果不完整'}[s.last_attempt_status]||s.last_attempt_status||'尚未执行')}。</p><p>${s.last_attempt_status==='partial'?'已完成部分的候选新增（未完成来源数量未知）':'本次候选新增'} ${s.last_attempt_status==='failed'?'检索失败，未知':(s.last_counts?.added??'未知')}；修订 ${s.last_counts?.revised??'未知'}；待复核 ${s.last_counts?.pending_total??data.candidates.length}；失败或受限 ${(s.last_errors||[]).length} 项。候选题录不计入已完成阅读的文献。</p>${s.last_link_audit?`<p>补充全文链接巡检：${date(s.last_link_audit.finished_at)}；尝试 ${s.last_link_audit.attempted} 个，目标题名已匹配 ${s.last_link_audit.title_matched} 个，受限或待核对 ${s.last_link_audit.unconfirmed} 个。检查结果见各条核验记录，不替代正文阅读。</p>`:''}${s.cloud_runtime?`<p>最近云端执行：${E(s.cloud_runtime.status)} · ${date(s.cloud_runtime.finished_at||s.cloud_runtime.started_at)} · ${link(s.cloud_runtime.run_url,'查看实际运行')}</p>`:''}${dep.data_version?`<p>最近核实发布版本：${E(dep.data_version)}</p>`:''}<div class="run-list">${(s.last_errors||[]).map(e=>`<p class="notice">${E(e.source)}：${E(e.reason)}</p>`).join('')}${Object.entries(s.source_progress||{}).map(([k,v])=>`<div>${E(k)} · ${date(v.last_success)}</div>`).join('')}</div>`;$('version').textContent='数据版本 '+data.data_version;}
function noteHTML(n){if(!n)return '<p class="notice">资料受限，尚不能形成可靠的内容笔记。</p>';return `<div class="note-section"><h3>研究问题</h3><p>${E(n.question)}</p></div><div class="note-section"><h3>研究设计与对象</h3><p>${E(n.design)}</p></div><div class="note-section"><h3>具体结果与内容要点</h3><ul>${(n.results||[]).map(x=>`<li>${E(x)}</li>`).join('')}</ul></div><div class="note-section"><h3>如何理解这篇文章 · 本库解读</h3><p>${E(n.interpretation)}</p></div><div class="note-section"><h3>局限与需要留意的地方</h3><ul>${(n.limitations||[]).map(x=>`<li>${E(x)}</li>`).join('')}</ul></div><div class="note-section"><h3>阅读依据与定位</h3><ol class="source-list">${(n.sources||[]).map(s=>`<li>${link(s.url,s.scope||'原文来源')} — ${E(s.locator)}</li>`).join('')}</ol><p class="fine">${E(n.read_depth)} · 本次阅读记录 ${date(n.reviewed_at)}。中文解读由模型辅助整理，冲突条目保留专业复核标记。</p></div>`;}
function auditHTML(r){const a=r.audit||{};const items=[['题录身份',a.identity?.status],['目标页面',a.page?.status],['全文',r.fulltext_status],['科学内容',a.content?.status]];if(r.video)items.push(['播放测试',r.video.playback_status],['嵌入测试',r.video.embed_status],['完整观看',r.video.watched?'已完整观看':'未完整观看']);return `<div class="audit-grid">${items.map(([k,v])=>`<div><b>${E(k)}</b>${E(v||'未核实')}</div>`).join('')}</div><p class="fine">本轮检查 ${date(r.last_checked)}；最近成功核验 ${date(r.last_successful_verification)}。各维度独立记录。</p>${(a.identity?.differences||[]).map(s=>`<p class="notice">${E(s)}</p>`).join('')}<p class="fine">目标终点：${link(a.page?.final_url||r.url,a.page?.final_url||r.url)}；HTTP ${E(a.page?.http_status??'未取得')}</p>${a.fulltext?.url?`<p class="fine">全文依据：${link(a.fulltext.url,a.fulltext.format||'来源')} · ${E(a.fulltext.status)}</p>`:''}${Object.keys(a.fulltext?.link_checks||{}).length?`<details><summary>全文来源独立巡检（${Object.keys(a.fulltext.link_checks).length} 个链接）</summary>${Object.entries(a.fulltext.link_checks).map(([u,c])=>`<p class="fine">${link(u,u)}<br>${E(c.status||'未确认')} · ${date(c.checked_at)} · HTTP ${E(c.http_status??'未取得')}${c.error?'<br>'+E(c.error):''}</p>`).join('')}</details>`:''}${(r.corrections||[]).length?`<p class="notice">出版更新或关联通知：${(r.corrections||[]).map(x=>E(x.type||x['update-type']||JSON.stringify(x))).join('；')}。请打开来源核对其适用内容。</p>`:''}${r.metadata_corrections?`<details><summary>本轮题录修订与依据</summary>${Object.entries(r.metadata_corrections.changes||{}).map(([k,v])=>`<p>${E(k)}：${E(v.before||'原字段为空')} → ${E(v.after)}</p>`).join('')}${(r.metadata_corrections.evidence||[]).map(e=>link(e.url,e.name)).join('；')}</details>`:''}<details><summary>历史核验与原始记录</summary><p class="fine">${E(r.history_text||'无历史核验说明')}（历史日期 ${E(r.history_date||'未知')}，不代表本轮复核。）</p>${(r.old_links||[]).map(u=>link(u,u)).join('<br>')}</details>`;}
function relations(r){const ids=[...(r.linked_article_ids||[]),...(r.linked_video_ids||[])];const official=ids.map(id=>data.records.find(x=>x.id===id)).filter(Boolean);const similar=data.records.filter(x=>x.id!==r.id&&!ids.includes(x.id)&&x.topic_ids.some(t=>r.topic_ids.includes(t))&&(r.kind==='article'?['video','course'].includes(x.kind):x.kind==='article')).slice(0,3);return (official.length?`<div class="note-section"><h3>官方配套文章 / 视频</h3>${official.map(x=>`<p><a href="#${E(x.id)}" data-go="${E(x.id)}">${E(x.zh_title||x.title)}</a></p>`).join('')}<p class="fine">同一出版物的文字和视频，不作为两项独立研究计数。</p></div>`:'')+(similar.length?`<details><summary>同主题资源（不表示同一研究或官方配套）</summary>${similar.map(x=>`<p><a href="#${E(x.id)}" data-go="${E(x.id)}">${E(x.zh_title||x.title)}</a></p>`).join('')}</details>`:'');}
function card(r,index){const n=r.note,v=r.video,saved=personal.favorites.includes(r.id);const primary=r.zh_title||n?.zh_title||r.title;const warning=r.verification_status!=='核心身份与所读内容已核对';return `<article class="card" id="${E(r.id)}"><div class="card-head"><div class="titles"><div class="chips">${chip(r.id)}${chip(r.resource_type)}${chip(n?.read_depth||r.verification_status,n?.read_depth==='正文重点核对'?'green':warning?'amber':'')}${chip(r.organ)}${n&&r.verification_status==='科学内容待专业复核'?chip('含待复核问题','amber'):''}</div><h2>${E(primary)}</h2>${primary!==r.title?`<p class="en-title">${E(r.title)}</p>`:''}<div class="meta">${E((r.authors||r.publisher||'作者/发布者待核').length>150?(r.authors||r.publisher).slice(0,145)+'…':(r.authors||r.publisher||'作者/发布者待核'))} · ${E(r.journal||r.source)} · ${E(r.year||'日期未知')}${r.doi?' · DOI '+E(r.doi):''}${r.pmid?' · PMID '+E(r.pmid):''}</div></div><button class="bookmark ${saved?'saved':''}" data-save="${E(r.id)}" aria-pressed="${saved}">${saved?'已收藏':'收藏'}</button></div>${v?`<p class="question">${E(v.summary)}</p><div class="video-meta">${[['术式',r.topic],['平台',r.source],['手术路径',r.approach],['视频类别',v.video_type],['语言',r.language_detail||r.language],['时长',v.duration],['可确认日期',v.date],['访问条件',v.access],['播放核验',v.playback_status]].map(([k,x])=>`<div><b>${E(k)}</b>${E(x||'未知')}</div>`).join('')}</div>`:`<p class="question">${E(n?.question||'来源受限；请查看该条记录的核验说明。')}</p><p class="preview">${E(n?.results?.[0]||'')}</p>`}<div class="actions">${link(r.url,v?'前往原站':'原文 / 题录')}${r.fulltext_url&&r.fulltext_url!==r.url?link(r.fulltext_url,'全文来源'):''}${v&&HPBCore.embedAllowed(r)?`<button data-play="${E(r.id)}">加载官方播放器</button>`:''}<a href="#${E(r.id)}" data-copy-id="${E(r.id)}">复制本条链接</a></div>${v?`<div class="player" data-player="${E(r.id)}"></div><p class="fine">${E(v.embed_status)}。${v.watched?'完整观看记录见核验依据。':'未完整观看；内容概括依据原站文字，不能视为已核实所有步骤。'}</p>`:`<details class="reading" ${index===0||location.hash==='#'+r.id?'open':''}><summary>展开完整阅读笔记</summary>${noteHTML(n)}</details>`}${relations(r)}${(r.article_relations||[]).map(rel=>`<p class="notice">${E(rel.type)}：${(rel.ids||[]).map(id=>`<a href="#${E(id)}" data-go="${E(id)}">${E(id)}</a>`).join('、')}</p>`).join('')}<details><summary>查看逐条核验记录</summary>${auditHTML(r)}</details><details><summary>我的补充笔记（仅本地保存）</summary><textarea class="personal" data-note="${E(r.id)}" aria-label="${E(r.id)}个人笔记">${E(personal.notes[r.id]||'')}</textarea><label class="fine"><input type="checkbox" data-read="${E(r.id)}" ${personal.read[r.id]?'checked':''}> 我已阅读</label></details></article>`;}
function coverage(){const cov=data.coverage||[];return `<article class="card"><h2>检索范围与实际缺口</h2><div class="actions"><button data-audit-export="records">导出逐条核验报告</button><button data-audit-export="coverage">导出覆盖与缺口报告</button></div><p class="coverage-note">当前库在所列来源、检索式和日期范围内整理。首次历史检索以指南、共识、随机试验和系统综述为重点，因此不等于全部原始研究已被检索；技术病例及中文资源仍需要官方目录补查。题录候选不计入已核实资源。</p><p class="coverage-note">固定程序检索 Europe PMC、PubMed，检查 SAGES 与 Stanford 官方目录；${E((data.methods?.manual_sources||[]).join('、'))}列为人工补查。${E((data.methods?.unsearched_subscription_sources||[]).join('、'))}本轮未完成授权检索。</p><details><summary>纳入规则、别名与可复现检索式</summary><p>${E(data.methods?.include)}</p><p>排除：${E(data.methods?.exclude)}</p><p>更新日期窗口重叠${E(data.methods?.overlap_days)}天，每月回看${E(data.methods?.monthly_lookback_days)}天；延迟收录防漏措施不构成绝不漏检保证。</p>${data.taxonomy.topics.map(t=>`<p><b>${E(t.label)}</b> · ${E(t.aliases.join(' / '))}<br><code>${E(t.query)}</code></p>`).join('')}</details><div class="table-scroll"><table><thead><tr><th>器官 / 专题</th><th>资源类型</th><th>已核实 / 受限</th><th>覆盖状态</th><th>检索依据</th></tr></thead><tbody>${cov.map(c=>`<tr><td>${E(c.organ)}<br><a href="#" data-topic="${E(c.topic_id)}">${E(c.topic)}</a></td><td>${E(c.type)}</td><td>${c.verified} / ${c.restricted}</td><td>${E(c.state)}</td><td>${(c.searches||[]).map(s=>`<details><summary>${E(s.source)} · ${s.complete?'已完成分页':'未完成'} · ${E(s.searched_at?.slice(0,10))}</summary><p>命中${s.hit_count??'未知'}；已返回${s.returned??'未知'}</p><code>${E(s.query)}</code></details>`).join('')||'尚无该类型独立检索记录'}<p class="fine">${E(c.gap)}</p></td></tr>`).join('')}</tbody></table></div></article>`;}
function render(){header();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('breadcrumb').textContent='全部资源'+(filters.organ?' / '+filters.organ:'')+(filters.topic_ids?' / '+(data.taxonomy.topics.find(t=>t.id===filters.topic_ids)?.label||filters.topic_ids):'')+(view==='all'?'':' / ')+({all:'',library:'阅读文库',videos:'视频库',recent:'最近更新',favorites:'我的收藏',coverage:'检索与覆盖',pending:'待核对与失效'}[view]||'阅读文库');if(view==='coverage'){$('result-count').textContent='覆盖矩阵按真实记录计算';$('content').innerHTML=coverage();$('pagination').innerHTML='';return;}
let rows=data.records.filter(r=>view==='videos'?['video','course','portal','lead'].includes(r.kind):view==='favorites'?personal.favorites.includes(r.id):view==='pending'?r.verification_status!=='核心身份与所读内容已核对':(view==='recent'||view==='all')?true:['article','society'].includes(r.kind));rows=HPBCore.select(rows,filters,q,data.taxonomy);if(view==='pending'){const cands=HPBCore.select(data.candidates||[],filters,q,data.taxonomy);rows=rows.concat(cands)}rows.sort((a,b)=>sort==='year'?(Number(b.year)||0)-(Number(a.year)||0):sort==='updated'||view==='recent'?String(b.last_checked||b.last_seen).localeCompare(String(a.last_checked||a.last_seen)):sort==='title'?a.title.localeCompare(b.title):(b.note?.read_depth==='正文重点核对')-(a.note?.read_depth==='正文重点核对')||(Number(b.year)||0)-(Number(a.year)||0));
const per=18,pages=Math.max(1,Math.ceil(rows.length/per));page=Math.min(page,pages);$('result-count').textContent=`${rows.length} 条结果 · 第 ${page} / ${pages} 页`;$('content').innerHTML=rows.length?rows.slice((page-1)*per,page*per).map((r,i)=>r.kind==='candidate'?`<article class="card" id="${E(r.id)}">${chip('新检索候选','amber')}<h2>${E(r.title)}</h2><p class="meta">${E(r.authors)} · ${E(r.journal)} · ${E(r.year)}</p><p>${E(r.content_status)}</p><p class="fine">${E(r.identity)}。首次发现 ${date(r.first_discovered)}；目标网页、全文和具体结论尚未核对。</p><div class="actions">${link(r.url,'查看原始题录')}${link(r.source_url||data.candidate_sources?.[r.source_ref],'查看检索来源')}</div></article>`:card(r,i)).join(''):'<div class="empty"><h2>没有符合当前条件的记录</h2><p>可以减少筛选条件，或查看该专题的检索缺口。没有收录不表示相关研究不存在。</p><button data-reset="true">重置筛选</button></div>';$('pagination').innerHTML=pages>1?`<button data-page="${page-1}" ${page===1?'disabled':''}>上一页</button><span>${page} / ${pages}</span><button data-page="${page+1}" ${page===pages?'disabled':''}>下一页</button>`:'';}
function reset(){filters={};q='';page=1;$('search').value='';filterUI();navUI();writeURL();render();}
function go(id){const r=data.records.find(x=>x.id===id);if(!r)return;view=['video','course','portal','lead'].includes(r.kind)?'videos':'library';filters={};q=id;$('search').value=id; // ID search is explicit and does not rely on clinical aliases.
 q='';$('search').value='';sort='title';$('sort').value=sort;const rows=data.records.filter(x=>view==='videos'?['video','course','portal','lead'].includes(x.kind):['article','society'].includes(x.kind)).sort((a,b)=>a.title.localeCompare(b.title));page=Math.floor(rows.findIndex(x=>x.id===id)/18)+1;location.hash=id;filterUI();writeURL(true);render();requestAnimationFrame(()=>$(id)?.scrollIntoView({block:'start'}));}
async function copy(text){try{await navigator.clipboard.writeText(text);$('connection').textContent='链接已复制。'}catch{$('connection').textContent='请从浏览器地址栏复制此链接：'+text}}
$('search').addEventListener('input',()=>{q=$('search').value;page=1;writeURL();render()});$('filters').addEventListener('change',e=>{if(e.target.dataset.filter){filters[e.target.dataset.filter]=e.target.value;page=1;writeURL();render()}});$('sort').addEventListener('change',()=>{sort=$('sort').value;page=1;writeURL();render()});$('reset').onclick=reset;$('copy-link').onclick=()=>{writeURL();copy(location.href)};
document.addEventListener('click',e=>{const b=e.target.closest('[data-view],[data-topic],[data-organ],[data-all],[data-save],[data-page],[data-go],[data-copy-id],[data-play],[data-reset]');if(!b)return;e.preventDefault();if(b.dataset.view){view=b.dataset.view;page=1;writeURL();render()}else if(b.dataset.topic){filters={topic_ids:b.dataset.topic};q='';$('search').value='';view='library';page=1;filterUI();navUI();writeURL();render()}else if(b.dataset.organ){filters={organ:b.dataset.organ};q='';$('search').value='';view='library';page=1;filterUI();writeURL();render()}else if(b.dataset.all){view='all';reset()}else if(b.dataset.reset){reset()}else if(b.dataset.save){const id=b.dataset.save;personal.favorites=personal.favorites.includes(id)?personal.favorites.filter(x=>x!==id):[...personal.favorites,id];persist();b.classList.toggle('saved');b.textContent=personal.favorites.includes(id)?'已收藏':'收藏';b.setAttribute('aria-pressed',personal.favorites.includes(id))}else if(b.dataset.page){page=Number(b.dataset.page);render();$('breadcrumb').scrollIntoView()}else if(b.dataset.go){go(b.dataset.go)}else if(b.dataset.copyId){const u=new URL(location.href);u.search='';u.hash=b.dataset.copyId;copy(u.href)}else if(b.dataset.play){const r=data.records.find(x=>x.id===b.dataset.play);if(!HPBCore.embedAllowed(r))return;const host=document.querySelector(`[data-player="${r.id}"]`);const frame=document.createElement('iframe');frame.src=r.video.embed_url;frame.title=r.title;frame.allow='fullscreen; picture-in-picture';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';host.replaceChildren(frame);const msg=document.createElement('p');msg.className='fine';msg.textContent='如播放器受网络或原站权限限制，请使用上方“前往原站”。加载完成不代表已能播放。';host.append(msg);b.disabled=true}});
document.addEventListener('input',e=>{if(e.target.dataset.note){personal.notes[e.target.dataset.note]=e.target.value;persist()}});
document.addEventListener('change',e=>{if(e.target.dataset.read){personal.read[e.target.dataset.read]=e.target.checked;persist()}});
$('menu').onclick=()=>{const yes=$('sidebar').classList.toggle('open');$('menu').setAttribute('aria-expanded',yes)};
document.addEventListener('click',e=>{const b=e.target.closest('[data-audit-export]');if(!b)return;const kind=b.dataset.auditExport;const out=kind==='records'?data.records.map(r=>({id:r.id,title:r.title,kind:r.kind,read_depth:r.read_depth,audit:r.audit,video:r.video,metadata_corrections:r.metadata_corrections,history:r.history_text})):data.coverage;const url=URL.createObjectURL(new Blob([JSON.stringify({domain_id:'hpb-surgery',data_version:data.data_version,generated_at:data.generated_at,records:out},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=kind==='records'?'肝胆胰_逐条核验报告.json':'肝胆胰_专题覆盖与缺口报告.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$('export-private').onclick=()=>{const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(personal,null,2)],{type:'application/json'}));a.href=url;a.download='肝胆胰_我的收藏与笔记.json';a.click();URL.revokeObjectURL(url)};
$('import-private').onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());if(p.domain_id!=='hpb-surgery'||p.schema_version!==1||!Array.isArray(p.favorites)||typeof p.notes!=='object'||!p.notes)throw Error('并非本库个人备份');const safe={};for(const[k,v]of Object.entries(p.notes))if(/^[A-Za-z0-9_.-]+$/.test(k)&&typeof v==='string')safe[k]=v;personal={...personal,favorites:Array.from(new Set([...personal.favorites,...p.favorites.filter(x=>typeof x==='string')])),notes:{...safe,...personal.notes},read:{...p.read,...personal.read}};persist();render();$('personal-status').textContent='已合并备份；当前浏览器中已有笔记优先保留。'}catch(err){$('personal-status').textContent='恢复失败：'+err.message}};
async function cloud(){const endpoint=trustedDeployment.https_base_url;if(!endpoint){$('connection').textContent='正在阅读本地内嵌版本。云端发布入口尚未配置，自动更新尚未启用。';return;}try{const u=new URL('data.json',endpoint.endsWith('/')?endpoint:endpoint+'/');if(u.protocol!=='https:')throw Error('云端入口必须使用HTTPS');$('connection').textContent='已显示内嵌版本，正在检查云端累计数据…';const control=new AbortController(),timer=setTimeout(()=>control.abort(),12000);let res;try{res=await fetch(u,{mode:'cors',credentials:'omit',cache:'no-store',signal:control.signal});if(!res.ok)throw Error('HTTP '+res.status);const text=await res.text();if(text.length>50000000)throw Error('数据过大');const next=await HPBCore.verifyEnvelope(JSON.parse(text),data,crypto);if(Date.parse(next.generated_at)<Date.parse(data.generated_at))throw Error('云端版本早于内嵌版本');data=next;}finally{clearTimeout(timer)}filterUI();navUI();render();$('connection').textContent='已读取并校验云端累计数据 · '+data.data_version;}catch(err){$('connection').textContent='云端读取失败，继续显示完整内嵌版本：'+err.message;}}
async function receipts(){
 for(const [key,kind] of [['status_url','publication'],['runtime_status_url','runtime']]){
  const endpoint=trustedDeployment[key];if(!endpoint)continue;const control=new AbortController(),timer=setTimeout(()=>control.abort(),10000);
  try{const u=new URL(endpoint);if(u.protocol!=='https:'||u.username||u.password)throw Error('状态入口无效');const res=await fetch(u,{mode:'cors',credentials:'omit',cache:'no-store',signal:control.signal});if(!res.ok)throw Error('状态请求HTTP '+res.status);const text=await res.text();if(text.length>2000000)throw Error('状态文件过大');const r=JSON.parse(text);if(r.domain_id!=='hpb-surgery'||r.schema_version!==1)throw Error('状态领域或结构不匹配');
   if(kind==='publication'){if(!r.deployed||!r.data_version||!Number.isFinite(Date.parse(r.verified_at)))throw Error('尚无有效发布回执');if(!data.state.last_successful_publish||Date.parse(r.verified_at)>=Date.parse(data.state.last_successful_publish)){data.state.last_successful_publish=r.verified_at;for(const k of ['deployed','schedule_enabled','observed_scheduled_run','verified_at','data_version'])if(k in r)data.deployment[k]=r[k];}}
   else {data.state.cloud_runtime=r;if(r.started_at&&Date.parse(r.started_at)>=Date.parse(data.state.last_attempt||0)){data.state.last_attempt=r.started_at;data.state.last_attempt_status=r.status;data.state.last_counts=r.last_counts||{};if(r.status==='failed'||r.status==='partial')data.state.last_errors=r.last_errors||[{source:'云端执行',reason:'运行未全部成功，见实际运行日志'}];}}
   header();
  }catch(err){$('connection').textContent+=' 状态回执暂不可读：'+err.message+'；保留原有时间记录。';}finally{clearTimeout(timer)}
 }
}
readURL();filterUI();navUI();render();if(!storageOK)$('personal-status').textContent='浏览器本地保存不可用，请用备份按钮保留本次笔记。';const hash=decodeURIComponent(location.hash.slice(1)).replace(/^resource-/,'');if(hash)go(hash);window.addEventListener('hashchange',()=>{const id=decodeURIComponent(location.hash.slice(1)).replace(/^resource-/,'');if(data.records.some(x=>x.id===id)&&!$(id))go(id)});cloud().finally(receipts);
})();
